import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h1>Welcome to My App</h1>
      <p>This is the homepage.</p>
    </div>
  );
}
